  // stack<int> s1;
    // s1.push(10);
    // s1.push(20);
    // s1.push(30);
    // s1.push(40);
    // s1.push(50);
    // s1.getsize();
    // s1.top();
    // cout<<"stack is Empty(1) or not(0): "<<s1.isEmpty()<<endl;
    // s1.pop();
    // s1.getsize();
    // s1.top();